### ISSUE TITLE
Request for SPI example 

### ISSUE THREAD

**Issue by fxj000** [microchip-pic-avr-examples/pic16f15244-bare-metal-i2c-mplab#1]
hi, I use PIC16F15244 SPI to read and write data to config a chip. Could you please share a SPI example for us, thank you so much. :)

**Comment by pic-avr-github-admin** [comment]
Hi @fxj000 ,
I released a bare metal SPI driver for the PIC16F15244: https://github.com/microchip-pic-avr-examples/pic16f15244-bare-metal-spi-mplab
The apps team also developed a SPI I/O expander example for the PIC16F15276 (larger pin count device) using the MCC libraries:
https://github.com/microchip-pic-avr-examples/pic16f15276-cnano-spi-io-expander-client-mplab-mcc
https://github.com/microchip-pic-avr-examples/pic16f15276-cnano-spi-io-expander-host-mplab-mcc
